== Задачки

* помещаем решения в `namespace cls08`

== Compile-time recursion [0.5 балла]

Реализуйте шаблонную структуру (от параметра size_t), хранящую в const static member (`value`) число Фибоначчи соответствующего индекса

== Functions

Реализовать 4 шаблонные функции (аналоги из стандартной библиотеки)

* Постарайтесь минимизировать требования к шаблонным типам
* Во всех заданиях диапазон вида `[begin, end)`
* За каждую функцию дается 0.25 балла

ifdef::backend-revealjs[=== !]

* `fill` - принимает два указателя на начало и конец диапазона и значение, которым заполнит этот диапазон
* `generate` - принимает два указателя на начало и конец диапазона и функцию-генератор значения
** каждый элемент из диапазона инициализирует отдельно сгенеренным значением

ifdef::backend-revealjs[=== !]

* `copy` - принимает три указателя: два на начало и конец диапазона источника (source) и один на начало диапазона назначения (destination)
* `for_each` - принимает два указателя на начало и конец диапазона и функтор. Выполняет функтор над каждым элементом

== Priority Queue

* Реализовать шаблонную очередь с приоритетами
** для поддержания порядка внутри очереди используйте кучу (алгоритм)
** можно использовать функции STL для работы с двоичной кучей

ifdef::backend-revealjs[=== !]
Необходимый интерфейс очереди:

* Конструктор, конструктор копирования, оператор=, деструктор
* Вставка в конец очереди `push(const T&)`
* Удаление первого элемента `void pop()`
* Доступ к первому элементу `/* ? */ front()`
* Размер очереди `size_t size()`

=== Custom Comparator[0.5 балла]

добавьте к очереди с приоритетами шаблонный параметр -- компаратор со значением по-умолчанию (см. `std::priority_queue`)
