CC=g++
CFLAGS=-Wall -Werror -std=c++2a

smoke_task_1:
	$(CC) $(CFLAGS) ./src/task_1/hello.cpp ./src/task_1/test.cpp -o smoke_task_1
	./smoke_task_1

smoke_task_2:
	$(CC) $(CFLAGS) ./src/task_2/fizzbuzz.cpp ./src/task_2/test.cpp -o smoke_task_2
	./smoke_task_2

smoke_task_3:
	$(CC) $(CFLAGS) ./src/task_3/compute_fib.cpp ./src/task_3/test.cpp -o smoke_task_3
	./smoke_task_3
