=== Задача №1. Hello World

Напишите и скомпилируйте программу с функцией `say_hello`, выводящей `Hello, world!` в стандартный вывод

Сигнатура функции:

[source,cpp]
----
void say_hello();
----

Объявите функцию в заголовочном файле `hello.hpp`, а её тело реализуйте в файле `hello.cpp`

=== Задача №2. Fizz Buzz

Напишите функцию, которая выводит на экран числа от `1` до `n`. Вместо чисел, кратных трем, программа должна выводить слово `Fizz`, а вместо чисел, кратных пяти — слово `Buzz`. Если число кратно пятнадцати, то программа должна выводить слово `FizzBuzz`

Сигнатура функции: 

[source,cpp]
----
void fizzbuzz(uint8_t n);
----

ifdef::backend-revealjs[=== !]

Объявите функцию в заголовочном файле `fizzbuzz.hpp`, а её тело реализуйте в файле `fizzbuzz.cpp`

ifdef::backend-revealjs[=== !]

Результат вызова `fizzbuzz(15)`: 
====

[source,cpp]
----
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
----
====

=== Задача №3

Напишите функцию `compute_fib`, считывающую из `input.txt` целое `N` и возвращающую `N`-ное число Фибоначчи

Число фибоначчи рекомендуется считать нерекурсивно

Сигнатура функции: 

[source,cpp]
----
int64_t compute_fib();
----

ifdef::backend-revealjs[=== !]

Объявите функцию в заголовочном файле `compute_fib.hpp`, а её тело реализуйте в файле `compute_fib.cpp`
